BEGIN TRANSACTION

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


BEGIN TRY
	CREATE TABLE [dbo].[Korisnici](
		[KorisniciID] [int] IDENTITY(1,1) NOT NULL,
		[Ime_i_prezime] [nvarchar](50) NULL,
		[Username] [nvarchar](50) NULL,
		[Password] [nvarchar](50) NULL,
	 CONSTRAINT [PK_Korisnici] PRIMARY KEY CLUSTERED 
	(
		[KorisniciID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]

	COMMIT TRANSACTION
END TRY
BEGIN CATCH
	PRINT ERROR_MESSAGE();
	PRINT 'Rollback is executed'
	ROLLBACK;
END CATCH