BEGIN TRANSACTION

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

BEGIN TRY
	CREATE TABLE [dbo].[Glumci](
		[GlumciID] [int] IDENTITY(1,1) NOT NULL,
		[Ime] [nvarchar](50) NULL,
		[Datum_rodjenja] [date] NULL,
		[Zemlja_porekla] [nvarchar](50) NULL,
		[Nagrade] [nvarchar](50) NULL,
	 CONSTRAINT [PK_Glumci] PRIMARY KEY CLUSTERED 
	(
		[GlumciID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]

	COMMIT TRANSACTION
END TRY
BEGIN CATCH
	PRINT ERROR_MESSAGE();
	PRINT 'Rollback is executed'
	ROLLBACK;
END CATCH