BEGIN TRANSACTION

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

BEGIN TRY
	CREATE TABLE [dbo].[Likovi](
		[LikoviID] [int] IDENTITY(1,1) NOT NULL,
		[FilmID] [int] NULL,
		[GlumciID] [int] NULL,
		[Ime] [nvarchar](50) NULL,
	 CONSTRAINT [PK_Likovi] PRIMARY KEY CLUSTERED 
	(
		[LikoviID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]

	ALTER TABLE [dbo].[Likovi]  WITH CHECK ADD  CONSTRAINT [FK_Likovi_Filmovi] FOREIGN KEY([FilmID])
	REFERENCES [dbo].[Filmovi] ([FilmID])

	ALTER TABLE [dbo].[Likovi] CHECK CONSTRAINT [FK_Likovi_Filmovi]

	ALTER TABLE [dbo].[Likovi]  WITH CHECK ADD  CONSTRAINT [FK_Likovi_Glumci] FOREIGN KEY([GlumciID])
	REFERENCES [dbo].[Glumci] ([GlumciID])

	ALTER TABLE [dbo].[Likovi] CHECK CONSTRAINT [FK_Likovi_Glumci]

	COMMIT TRANSACTION
END TRY
BEGIN CATCH
	PRINT ERROR_MESSAGE();
	PRINT 'Rollback is executed'
	ROLLBACK;
END CATCH
